### ISSUE TITLE
Ambiguous bug

### ISSUE THREAD

**Issue by ludodv** [RemonZander/Group-5#11]
![image](https://user-images.githubusercontent.com/31469881/118838932-6015aa00-b8c6-11eb-9a4c-ad792602f75f.png)
![image](https://user-images.githubusercontent.com/31469881/118839029-74f23d80-b8c6-11eb-9aac-5a1d62f7f78e.png)
Type something like "Rémon" and try to use backspace.

**Comment by QuinnRachman** [comment]
Fixed
