### ISSUE TITLE
When reservation message doesn't contain any spaces

### ISSUE THREAD

**Issue by ludodv** [RemonZander/Group-5#13]
![image](https://user-images.githubusercontent.com/31469881/118842539-97d22100-b8c9-11eb-8d5b-a04fc5de0291.png)
![image](https://user-images.githubusercontent.com/31469881/118842651-b20bff00-b8c9-11eb-90c6-52b883fce959.png)
![image](https://user-images.githubusercontent.com/31469881/118842806-cd770a00-b8c9-11eb-9ee9-13087d41acd1.png)

**Comment by RemonZander** [comment]
0de59c89a5b4d13a9871ea78cf4263b6785bdea3 - fixed
