### ISSUE TITLE
Copy paste bug?

### ISSUE THREAD

**Issue by ludodv** [RemonZander/Group-5#23]
Step 1
![image](https://user-images.githubusercontent.com/31469881/120213380-69dace00-c233-11eb-810e-e0132119f440.png)
Step 2
![image](https://user-images.githubusercontent.com/31469881/120213423-78c18080-c233-11eb-9faf-67d934c86926.png)
Step 3
![image](https://user-images.githubusercontent.com/31469881/120213456-84ad4280-c233-11eb-8b2a-9565c7e927bf.png)

**Comment by QuinnRachman** [comment]
Fixed - https://github.com/RemonZander/Group-5/commit/d856f7cfd2c81b82c578fb52e0153e4be4906080
