### ISSUE TITLE
Als je op escape drukt return je van het gerechten menu van de eigenaar naar review menu van de klant

### ISSUE THREAD

**Issue by RemonZander** [RemonZander/Group-5#28]
![image](https://user-images.githubusercontent.com/63671491/120320994-132ccd00-c2e3-11eb-852e-9093d800da57.png)
Als je één van deze opties kiest en dan op esc drukt dan ga je naar het verkeerde menu. Ook kan je geen 1 indrukken als geldige optie

**Comment by QuinnRachman** [comment]
Fixed - https://github.com/RemonZander/Group-5/commit/4be2b37b95d61efd27b2a619c857ac0745df47eb
