### ISSUE TITLE
Registreerscherm nieuw wachtwoord invoeren

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#33]
Wanneer je wachtwoord niet voldoet aan de eisen, moet je opnieuw een wachtwoord invoeren.

De oude wachtwoordline weghalen gaat wrs n hel worden, dus idk maybe kan je dr gwn n "\n" onder zetten endan
"Het nieuwe wachtwoord voor uw account: "

Gwn n idee voor de duidelijkheid, laatmaar weten watje doet :)

![image](https://user-images.githubusercontent.com/79160513/120488448-12656b00-c3b7-11eb-91f9-faf1357d6971.png)

**Comment by QuinnRachman** [comment]
Fixed
