### ISSUE TITLE
Review schrijven scherm (klant)

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#48]
"Hier kunt u een review maken." => "Hier kunt u een oude reservering kiezen, waarover u een review wilt schrijven."

"U kunt een review schrijven per reservering." => "U kunt één review schrijven per reservering."

"U kunt kiezen uit een van de volgende reserveringen:" => "\nU kunt kiezen uit één van de onderstaande reserveringen:"

"datum" => "Datum"

"Met het ID kunt u selecteren over welk bezoek u een review wilt schrijven." => "U kunt d.m.v. het invullen van een ID een reservering selecteren, waarover u een review wilt schrijven."

"Het ID van u reservering:" => "De ID van uw reservering:" (ja ik meen het... het is de id hahaha)

![image](https://user-images.githubusercontent.com/79160513/120616190-4f823980-c459-11eb-9e86-9b050eed788a.png)

**Comment by RemonZander** [comment]
fixed
