### ISSUE TITLE
Review schrijven scherm (klant) - foutmelding

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#49]
"U moet wel een juist ID selecteren" => "U moet wel een juist ID selecteren."
"Druk op een knop om verder te gaan..." => "Druk op een toets om verder te gaan."

![image](https://user-images.githubusercontent.com/79160513/120617522-768d3b00-c45a-11eb-94ed-1eb16c45493d.png)

**Comment by RemonZander** [comment]
fixed
