### ISSUE TITLE
Review schrijven scherm (klant) - anoniem/normaal keuze

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#50]
"Er is een mogelijkheid om anoniem een review te geven, anoniem houdt in:" => "Het is mogelijk om anoniem een review te schrijven, anoniem houdt in:"

"-> U naam word niet opgeslagen met de review." => "-> Uw naam wordt niet opgeslagen bij de review."

"-> De review word niet gekoppeld aan deze reservering." -> "-> De review wordt niet gekoppeld aan deze reservering."

"-> U kunt deze review niet aanpassen of verwijderen." => "-> U kunt deze review niet bewerken en/of verwijderen."

![image](https://user-images.githubusercontent.com/79160513/120617779-b94f1300-c45a-11eb-86a8-9451d121d934.png)

**Comment by RemonZander** [comment]
fixed
