### ISSUE TITLE
Review schrijven scherm (klant) - anoniem schrijven

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#51]
"De beoordeling die u dit restaurant wilt geven van 1 tot 5 waarin, 1 is het slechtste en 5 is het beste" => "Op een schaal van 1 t/m 5 (slechtst naar best), welke beoordeling zou u uw ervaring in het restaurant geven?"

"Als laatste, de inhoud van u review. Een review mag niet langer zijn dan 160 tekens." => "\nHieronder kunt u de inhoud van uw review schrijven (max. 160 tekens). Wilt u dit niet, druk dan op enter."

"De inhoud van de review:" => kan helemaal weg

"Succesvol een review gemaakt." => "\nSuccesvol een review aangemaakt."

![image](https://user-images.githubusercontent.com/79160513/120618530-76416f80-c45b-11eb-8b22-e1c3298493ed.png)

**Comment by RemonZander** [comment]
fixed
