### ISSUE TITLE
Review schrijven (klant) - foutmelding onjuiste beoordeling

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#52]
"U heeft een incorrecte beoordeling ingevoerd." => "\nU heeft een incorrecte beoordeling ingevoerd."

"Druk op een knop om terug te gaan." => "Druk op een toets om terug te gaan."
![image](https://user-images.githubusercontent.com/79160513/120620142-f6b4a000-c45c-11eb-88c0-4abd851fe8cb.png)

**Comment by RemonZander** [comment]
fixed
