### ISSUE TITLE
Review schrijven (klant) - normaal schrijven

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#53]
"De beoordeling die u dit restaurant wilt geven van 1 tot 5 waarin: 1 het slechtste is en 5 het beste." => "Op een schaal van 1 t/m 5 (slechtst naar best), welke beoordeling zou u uw ervaring in het restaurant geven?"

"Als laatste, de inhoud van u review." => mag helemaal weg

"Met Enter gaat u verder op een nieuwe regel. Een review mag niet langer zijn dan 160 tekens. => "\nHieronder kunt u de inhoud van uw review schrijven (max. 160 tekens). Wilt u verder typen op een nieuwe regel, druk dan op enter."

"Als u klaar bent met het typen van u review, type dan "klaar" op een nieuwe regel." => "Als u klaar bent met het schrijven van uw review, typ dan 'klaar' op een nieuwe regel."

"De inhoud van de review:" => mag helemaal weg

![image](https://user-images.githubusercontent.com/79160513/120620592-688ce980-c45d-11eb-8efe-2160b3675d08.png)

**Comment by RemonZander** [comment]
Deze report had je al aangemaakt?
