### ISSUE TITLE
Je kan een review schrijven van meer dan 160 tekens

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#54]
Wnnr je anoniem een review schrijft metmeer dan 160 tekens krijg je wel n foutmelding.
Als je gwn normaal n review schrijft metmeer dan 160 tekens maakt ie gwn n review aan.

![image](https://user-images.githubusercontent.com/79160513/120621709-6aa37800-c45e-11eb-9365-8eccf369058d.png)

**Comment by RemonZander** [comment]
fixed (Ik had het alleen nog maar gefixt voor anoniem)
