### ISSUE TITLE
Review schrijven (klant) - anoniem schrijven foutmelding

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#55]
"Uw bericht mag niet langer zijn dan 160 tekens." => "Uw review mag niet langer zijn dan 160 tekens.\nHieronder kunt u opnieuw een review schrijven."

"Druk op een toets om terug te gaan." => "Druk op een toets om terug te keren naar het klantenmenu."

![image](https://user-images.githubusercontent.com/79160513/120622163-dc7bc180-c45e-11eb-87e1-bacf0c3c281b.png)

**Comment by RemonZander** [comment]
fixed
