### ISSUE TITLE
Reviews (klant) - alle reviews

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#72]
Onder "Dit zijn uw reviews op pagina 1 vd 4:" moet je ff dit schrijven:
"Gebruik de pijltjestoetsen om te navigeren door uw reviews."
"De review met de tekst 'Bewerken' en 'Verwijderen' is de huidig geselecteerde review."
↑ doe dit ook ff bij reviews selecteren op datum & reviews selecteren op beoordeling :)

"Rating: " => "Beoordeling: "

![image](https://user-images.githubusercontent.com/79160513/120642530-4d2dd880-c475-11eb-808b-004e31d0f6ed.png)

**Comment by QuinnRachman** [comment]
ReviewsToString method wordt gebruikt van Remon
