### ISSUE TITLE
Reserveringen bekijken (medewerker)

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#82]
zet ff onder "Pagina 1 van de 2:" dit neer ↓
"Gebruik de pijltjestoetsen om te navigeren door de reserveringen.\nDe reservering met de tekst 'Tafels koppelen' is de huidig geselecteerde reservering."

mag "[6] Toon alleen de reserveringen zonder tafel" onder "[3] Vorige dag             [4] Volgende dag             [5] Naar vandaag" komen te staan pls :)

" U moet wel een juiste keuze maken..." => "U heeft een ongeldig antwoord gegeven."
"Druk op en knop om verder te gaan." => "Druk op een toets om het opnieuw te proberen."

![image](https://user-images.githubusercontent.com/79160513/120781754-a6efda80-c529-11eb-80b6-62eea3c4a596.png)

**Comment by ludodv** [comment]
Ik laat
`Gebruik de pijltjestoetsen om te navigeren door de reserveringen.
De reservering met de tekst 'Tafels koppelen' is de huidig geselecteerde reservering.`
Zien als er meer dan 1 item is
