### ISSUE TITLE
klik op enter?

### ISSUE THREAD

**Issue by DePaWSiT** [RemonZander/Group-5#92]
![image](https://user-images.githubusercontent.com/62265443/121169095-f00a9c00-c853-11eb-869e-dcb27498ec4c.png)

Geef nu aan de allergenen van het gerecht, als u geen allergenen wilt aangeven of als u klaar bent type dan in klaar en klik op enter -> Geef nu aan de allergenen van het gerecht, als u geen allergenen wilt aangeven of als u klaar bent, typ dan in  klaar  en druk op enter

**Comment by QuinnRachman** [comment]
Fixed
