### ISSUE TITLE
Menukaart spelfouten

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#93]
"Welkom bij het menukaart!" => "Welkom bij de menukaart!"

"[1] Laat alle ontbijt gerechten zien." => "[1] Ontbijt"
"[2] Laat alle lunch gerechten zien." => "[2] Lunch"
"[3] Laat alle diner gerechten zien." => "[3] Diner" (op andere plekken zal 'avondeten' staan, dus als we consistent willen blijven, moeten we dat ook ff veranderen naar 'diner')
"[4] Laat alle dranken zien" => "[4] Dranken"

![image](https://user-images.githubusercontent.com/79160513/121176207-3e239d80-c85c-11eb-8abf-ae4fa3601471.png)

-----------------------------------------------------------------------------------------------------
Kunnen er paginanummers worden toegevoegd aan de volgende schermen: Ontbijtscherm, lunchscherm, dinerscherm en drankenscherm. Zie voorbeeld hieronder ↓

"U bevindt zich op pagina 2 van de 5:  "
-----------------------------------------------------------------------------------------------------

**OPTIE 1 - ONTBIJT**

"Welkom bij het menukaart, hier kunt u alle gerechten bekijken." => "Welkom bij de ontbijtkaart, hier kunt u alle gerechten bekijken."

![image](https://user-images.githubusercontent.com/79160513/121178399-bc813f00-c85e-11eb-8ffd-de63a8d59225.png)

------------------------------------------------------------------------------------------------------

**OPTIE 2 - LUNCH**

"Welkom bij het menukaart, hier kunt u alle gerechten bekijken." => "Welkom bij de lunchkaart, hier kunt u alle gerechten bekijken."

![image](https://user-images.githubusercontent.com/79160513/121178573-e9355680-c85e-11eb-8e03-81f12d7dab83.png)

-----------------------------------------------------------------------------------------------------

**OPTIE 3 - DINER**

"Welkom bij het menukaart, hier kunt u alle gerechten bekijken." => "Welkom bij de dinerkaart, hier kunt u alle gerechten bekijken."

![image](https://user-images.githubusercontent.com/79160513/121178689-15e96e00-c85f-11eb-8253-013e8e9dbd0e.png)

------------------------------------------------------------------------------------------------------

**OPTIE 4 - DRANKEN**

"Welkom bij het menukaart, hier kunt u alle gerechten bekijken." => "Welkom bij de drankenkaart, hier kunt u alle dranken bekijken."

![image](https://user-images.githubusercontent.com/79160513/121178891-4f21de00-c85f-11eb-94e9-45a7fd6c5596.png)

**Comment by QuinnRachman** [comment]
Fixed
