### ISSUE TITLE
Gerechten bekijken/bewerken/archiveren/verwijderen scherm

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#95]
"Gebruik de pijltjestoetsen om door de items in de vakjes te gaan.\nDe geselecteerde item heeft extra opties vergeleken met de rest."

↓

"Gebruik de pijltjestoetsen om te navigeren door de gerechten.\nHet gerecht met de tekst 'Bekijken', 'Bewerken', 'Archiveren' en 'Verwijderen' is het huidig geselecteerde gerecht."

"[5] Bewerk" => "[5] Bewerken"
"[6] Archiveer" => "[7] Archiveren" (was eerst nr. 6)
'[7] Verwijderen" => "[6] Verwijderen" (was eerst nr. 7)

![image](https://user-images.githubusercontent.com/79160513/121179462-15050c00-c860-11eb-92b4-14e220cd504a.png)

------------------------------------------------------------------------------------------------------

"Dit is het geselecteerde gerecht dat u wilt archiveren." => "Hierboven ziet u het huidig geselecteerde gerecht."

"Weet u zeker dat u deze gerecht wilt archiveren?  ja  |  nee" => "Weet u zeker dat u dit gerecht wilt archiveren?  ja  |  nee"

![image](https://user-images.githubusercontent.com/79160513/121180833-95783c80-c861-11eb-8c49-8ddd3f6eb1b1.png)

------------------------------------------------------------------------------------------------------

"Dit is het geselecteerde gerecht dat u wilt verwijderen." => "Hierboven ziet u het huidig geselecteerde gerecht."

"Weet u zeker dat u deze gerecht wilt verwijderen?  ja  |  nee" => "Weet u zeker dat u dit gerecht wilt verwijderen?  ja  |  nee"

![image](https://user-images.githubusercontent.com/79160513/121181043-dec88c00-c861-11eb-9a9b-30b4cb6b3369.png)

**Comment by QuinnRachman** [comment]
Fixed
