### ISSUE TITLE
Gerechten filteren (ontbijt/lunch/diner)

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#96]
"Op welk type wilt u sorteren? Type in Ontbijt/Lunch/Diner" => "\nOp welk type wilt u sorteren? Typ 'ontbijt', 'lunch' of 'diner'."

![image](https://user-images.githubusercontent.com/79160513/121181440-4d0d4e80-c862-11eb-8c1c-3be617117d01.png)

**Comment by QuinnRachman** [comment]
Fixed
