### ISSUE TITLE
Optie inkomsten showt alleen uitgaven + esc werkt niet

### ISSUE THREAD

**Issue by LuennaCL** [RemonZander/Group-5#99]
Eigenaar optie 8 (inkomsten) showt alleen uitgaven.
Esc knop werkt niet.

![image](https://user-images.githubusercontent.com/79160513/121183485-69aa8600-c864-11eb-9625-a95d728d8f3e.png)

**Comment by RemonZander** [comment]
Optie uitgaven staat ook niet eens in ownermenuscreen.
case 8:
    return 13;
moet worden:
case 8:
    return 15;
En optie voor uitgaven toevoegen. Dat is scherm 13

**Comment by QuinnRachman** [comment]
Fixed
